name: Release and Publish to NPM
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Init git user
        run: |
          git config --global user.name "Antharuu"
          git config --global user.email "antho.eclips@gmail.com"
      - name: Bad practice
        run: echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}"
      - name: Configure npm
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
      - name: Release
        run: yarn up
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: End message
        run: echo "End of release"
